import * as actionTypes from "../actions/handlePhoto"

const initialState = {
    loading:false,
    error:false,
    photosData:[],
    userPhotoList:[],
    userPhotoPost:null, 
    profilePhoto:null 
}

const reducer = (state = initialState,action) => {
    switch(action.type){
        case(actionTypes).GET_RANDOM_PHOTOS_START:
            return{
                ...state,
                loading:true
            }
        case(actionTypes).GET_RANDOM_PHOTOS_SUCCESS:
            return{
                ...state,
                loading:false,
                error:false,
                photosData:action.photosData
            }
        case(actionTypes).GET_RANDOM_PHOTOS_FAIL:
            return{
                ...state,
                loading:false,
                error:action.error
            }
        case(actionTypes).UPLOAD_PHOTO_START:
            return{
                ...state,
                loading:true
            }
        case(actionTypes).UPLOAD_PHOTO_SUCCESS:
            return{
                ...state,
                loading:false,
                error:false,
                userPhotoList:[...state.userPhotoList,action.url]
            }
        case(actionTypes).UPLOAD_PHOTO_FAIL:
            return{
                ...state,
                loading:false,
                error:action.error
            }
        case(actionTypes).UPLOAD_PROFILE_PHOTO_START:
            return{
                ...state,
                loading:true
            }
        case(actionTypes).UPLOAD_PROFILE_PHOTO_SUCCESS:
            return{
                ...state,
                loading:false,
                error:false,
                profilePhoto:action.profilePhoto
            }
        case(actionTypes).UPLOAD_PROFILE_PHOTO_FAIL:
            return{
                ...state,
                loading:false,
                error:action.error
            }
        case(actionTypes).GET_PHOTO_START:
            return{
                ...state,
            }
        case(actionTypes).GET_PHOTO_SUCCESS:
            return{
                ...state,
                loading:false,
                error:false,
                userPhotoList:action.data,
                userPhotoPost:null
            }
        case(actionTypes).GET_PHOTO_FAIL:
            return{
                ...state,
                loading:false,
                error:action.error
            }
        case(actionTypes).GET_PROFILE_PHOTO_START:
            return{
                ...state,
                loading:true
            }
        case(actionTypes).GET_PROFILE_PHOTO_SUCCESS:
            return{
                ...state,
                loading:false,
                error:false,
                profilePhoto:action.profilePhoto
            }
        case(actionTypes).GET_PROFILE_PHOTO_FAIL:
            return{
                ...state,
                loading:false,
                error:action.error
            }
        case(actionTypes).UPLOAD_PHOTO_IN_HOME:
            return{
                ...state,
                userPhotoPost:action.url
            }
        default :
            return state
    }
}

export default reducer